version: "3.7"

services:
  
  ingest-api: 
    # Use the published image and tag from DockerHub
    image: sennet/ingest-api:${INGEST_API_VERSION:?err}
    volumes:  
      # Mount the VERSION file and BUILD file 
      - "../VERSION:/usr/src/app/VERSION" 
      - "../BUILD:/usr/src/app/BUILD" 
      # Mount data directory for Globus transfer PROD
      - "/codcc/data:/codcc/data"

  ingest-api-rq-worker:
    build:
      context: ./ingest-api
      dockerfile: ./rq/Dockerfile
    image: sennet/ingest-api-rq-server:${INGEST_API_VERSION:?err}
    volumes:
      # Mount the VERSION file and BUILD file 
      - "../VERSION:/usr/src/app/VERSION" 
      - "../BUILD:/usr/src/app/BUILD" 
      # Mount data directory for Globus transfer PROD
      - "/codcc/data:/codcc/data"
      - "/codcc/scratch:/codcc/scratch"
    deploy:
      replicas: 4
    networks:
      - sennet_docker_network
