version: "3.7"

services:

  ingest-api:
    # Use the published image and tag from DockerHub
    image: sennet/ingest-api:${INGEST_API_VERSION:?err}
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount data directory for Globus transfer PROD
      - "/codcc/data:/codcc/data"
      - "/codcc/scratch:/codcc/scratch"

  ingest-api-rq-worker:
    build:
      context: ./ingest-api
      dockerfile: ./rq/Dockerfile
    image: sennet/ingest-api-rq-server:${INGEST_API_VERSION:?err}
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount data directory for Globus transfer PROD
      - "/codcc/data:/codcc/data"
      - "/codcc/scratch:/codcc/scratch"
    deploy:
      replicas: 4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - sennet_docker_network
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: ingest-api-rq-worker-docker-logs
        awslogs-stream: ${LOG_STREAM}

  ingest-api-rq-server:
    image: redis:alpine
    hostname: ingest-api-rq-server
    container_name: ingest-api-rq-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - sennet_docker_network
