name: Tests

on:
  push:
    branches: [ 88-create-pyunit-tests-for-ingest-api ]
  pull_request:
    branches: [ 88-create-pyunit-tests-for-ingest-api ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install --no-deps -r src/routes/validation/ingest_validation_tools/requirements.in
      - name: Test with pytest
        run: |
          pytest -W ignore::DeprecationWarning 
